#ifndef __tlineLogic__
#define __tlineLogic__

#include <complex>

using namespace std;

#include "cableTypes.h"

/**
@file
Subclass of tline, which is generated by wxFormBuilder.
*/

#include "tlineUI.h"

//// end generated include

/** Implementing tline */
class tlineLogic : public tlineUI
{
	public:
		/** Constructor */
		tlineLogic( wxWindow* parent );
	//// end generated class members

	private:
		void onCableTypeSelected( wxCommandEvent& event );
		void onFileExit( wxCommandEvent& event );
		void onUnitsSelected( wxCommandEvent& event );
		void onFrequencySelected( wxCommandEvent& event );
		void onLengthSelected( wxCommandEvent& event );

		double wavelength();

		void recalculate();

		inline double sq(
				double v
				)
		{
			return v * v;
		}

		cableTypes		*m_c;
		CABLE_PROPERTIES	*m_cp;

		wxString		m_cableTypeStr = _("RG-6 (Belden 8215)");
		wxString		m_unitsStr = _("Feet");
		wxString		m_frequencyStr = _("7.0");
		wxString		m_lengthStr = _("100");

		double			m_units;
		double			m_atten;
		double			m_frequency;
		double			m_length;
		double			m_phase;
		double			m_cableResistivePart;
		double			m_cableReactivePart;
		double			m_wavelength;

		std::complex<double>	m_lossCoef;
		std::complex<double>	m_zCable;
};

#endif // __tlineLogic__
