#ifndef __tlineLogic__
#define __tlineLogic__

/**
@file
Subclass of tline, which is generated by wxFormBuilder.
*/

#include "tlineUI.h"

//// end generated include

/** Implementing tline */
class tlineLogic : public tlineUI
{
	public:
		/** Constructor */
		tlineLogic( wxWindow* parent );
	//// end generated class members

};

#endif // __tlineLogic__
